dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

stages:
  - test
  - integration-test

sudo: false

jobs:
  include:
    - stage: integration-test
      script: |
        sudo echo '{"insecure-registries": ["172.30.0.0/16"]}' > daemon.json
        sudo mv daemon.json /etc/docker
        sudo cat /etc/docker/daemon.json
        sudo service docker restart
        ./startOCP.sh 3.9.101
        mvn verify -Pintegration-tests
        ./oc cluster down
        ./startOCP.sh 3.10.175
        mvn verify -Pintegration-tests
        ./oc cluster down
        ./startOCP 3.11.146
        mvn verify -Pintegration-tests
        ./oc cluster down
