dist: trusty

language: java

jdk:
  - oraclejdk8
  - oraclejdk11

stages:
  - test
  - integration-test

sudo: false

jobs:
  include:
    - stage: integration-test
      script: |
        for OCP in 3.9.101 3.10.175 3.11.146;
        do
        echo $OCP
        curl https://mirror.openshift.com/pub/openshift-v3/$OCP/linux/oc.tar.gz --location --output oc.tar.gz
        gunzip oc.tar.gz
        tar -xvf oc.tar
        sudo echo '{"insecure-registries": ["172.30.0.0/16"]}' > daemon.json
        sudo mv daemon.json /etc/docker
        sudo cat /etc/docker/daemon.json
        sudo service docker restart
        ./oc cluster up
        mvn verify -Pintegration-tests
        ./oc cluster down
        done